edition = "2021"
tab_spaces = 2
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
reorder_imports = true
unstable_features = true
condense_wildcard_suffixes = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
