import { createRequire } from "module";
import { dirname, sep } from "path";
const __dirname = dirname(decodeURIComponent(import.meta.url.slice(sep=='/'? 7:8)));
const require = createRequire(import.meta.url);/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

import { existsSync, readFileSync } from 'fs'
import { join } from 'path'

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'clip_img2qdrant.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./clip_img2qdrant.android-arm64.node')
          } else {
            nativeBinding = require('@w5/clip_img2qdrant-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'clip_img2qdrant.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./clip_img2qdrant.android-arm-eabi.node')
          } else {
            nativeBinding = require('@w5/clip_img2qdrant-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'clip_img2qdrant.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./clip_img2qdrant.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@w5/clip_img2qdrant-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'clip_img2qdrant.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./clip_img2qdrant.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@w5/clip_img2qdrant-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'clip_img2qdrant.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./clip_img2qdrant.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@w5/clip_img2qdrant-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'clip_img2qdrant.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./clip_img2qdrant.darwin-universal.node')
      } else {
        nativeBinding = require('@w5/clip_img2qdrant-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'clip_img2qdrant.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./clip_img2qdrant.darwin-x64.node')
          } else {
            nativeBinding = require('@w5/clip_img2qdrant-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'clip_img2qdrant.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./clip_img2qdrant.darwin-arm64.node')
          } else {
            nativeBinding = require('@w5/clip_img2qdrant-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'clip_img2qdrant.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./clip_img2qdrant.freebsd-x64.node')
      } else {
        nativeBinding = require('@w5/clip_img2qdrant-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'clip_img2qdrant.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./clip_img2qdrant.linux-x64-musl.node')
            } else {
              nativeBinding = require('@w5/clip_img2qdrant-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'clip_img2qdrant.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./clip_img2qdrant.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@w5/clip_img2qdrant-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'clip_img2qdrant.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./clip_img2qdrant.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@w5/clip_img2qdrant-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'clip_img2qdrant.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./clip_img2qdrant.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@w5/clip_img2qdrant-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        localFileExisted = existsSync(
          join(__dirname, 'clip_img2qdrant.linux-arm-gnueabihf.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./clip_img2qdrant.linux-arm-gnueabihf.node')
          } else {
            nativeBinding = require('@w5/clip_img2qdrant-linux-arm-gnueabihf')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

;
const add = nativeBinding.Db.prototype.add;

nativeBinding.Db.prototype.add = function (id, payload, img, ext){
  return add.call(this,id,JSON.stringify(payload),img,ext)
} 

nativeBinding.Db = new Proxy(
  {},
  {
    get:(_,name)=>nativeBinding.dbNew(name)
  }
)



/*
import autoe from "@w5/utf8/autoe.js";
import { u8merge } from "@w5/u8";

const { z85Dump: _z85Dump, zipU64: _zipU64 } = nativeBinding;

const autoeLi = new Proxy(
	{},
	{
		get: (_, name) => {
			const func = nativeBinding[name];
			nativeBinding[name] = (...args) => {
				return func(u8merge(...args.map(autoe)));
			};
			return;
		},
	},
);

autoeLi.passwordHash;
autoeLi.cookieEncode;

nativeBinding.z85Dump = (s) => _z85Dump(autoe(s));
nativeBinding.zipU64 = (...args) => _zipU64(args);
*/

// const _Db = nativeBinding.Db;
//
// nativeBinding.Db = (name)=>
//   new _Db(name)
//
//

export const Db = nativeBinding.Db;
export const dbNew = nativeBinding.dbNew;