version: '3'

services:
  clip-qdrant:
    container_name: clip-qdrant
    image:  qdrant/qdrant
    restart: always
    volumes:
      - ./qdrant/data:/qdrant/storage
      - ./qdrant/config.yml:/qdrant/config/config.yaml
    ports:
      - ${QDRANT_grpc_port}:${QDRANT_grpc_port}
      - ${QDRANT_http_port}:${QDRANT_http_port}

