/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class Arr {
  raw(): any
  len(): bigint
  shape(): any
}
export class Model {
  constructor(dir: string)
  txt(onnx: string, contextLength: number): Txt
}
export class Txt {
  encode(txt: Array<string> | string): Arr
}
